name: Build

on:
  push:
    branches:
      - master
      - develop
    paths-ignore:
      - '.idea/**'
  pull_request:
    branches:
      - master
      - develop
    paths-ignore:
      - '.idea/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v2

        # Robolectric needs Java 9+ to run tests with Android 10. On Java 12+, it fails.
        # JDK 11 has fixes for Room. See https://bugs.openjdk.java.net/browse/JDK-8007720
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Generate cache key
        run: ./checksum.sh checksum.txt

      - name: Copy CI gradle.properties
        run: |
          mkdir -p ~/.gradle
          cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Restore Gradle cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradlecache-${{ hashFiles('checksum.txt') }}
          restore-keys: |
            ${{ runner.os }}-gradlecache-

      - name: Restore Gradle dist cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper/dists
          key: ${{ runner.os }}-gradledist-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradledist-

      - name: Restore robolectric cache
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository/org/robolectric/android-all
          key: ${{ runner.os }}-robolectric-${{ hashFiles('test-shared/src/main/resources/robolectric.properties') }}
          restore-keys: |
            ${{ runner.os }}-robolectric-

      - name: Generate build number
        uses: einaregilsson/build-number@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}

      - name: Check code
        run: ./gradlew dependencyUpdates spotlessCheck app:lintDebug --stacktrace

      - name: Test
        run: ./gradlew testDebugUnitTest jacocoTestReportDebug --stacktrace

      - name: Build
        run: ./gradlew app:assembleDebug app:assembleRelease -Papp.versionCode=$BUILD_NUMBER

      - name: Upload build outputs
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: build-outputs
          path: app/build/outputs

      - name: Upload build reports
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: build-reports
          path: app/build/reports

      - name: Upload dependency updates report
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: dependency-updates
          path: build/dependencyUpdates

      - name: Copy test results
        if: always()
        run: |
          mkdir -p junit
          find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} junit/ \;

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: junit-results
          path: junit

      - name: Copy schemas
        run: |
          mkdir -p schemas
          find . -type d -regex ".*/schemas/com\.insiderser.*" -exec cp {} schemas/ \;

      - name: Upload Room schemas
        uses: actions/upload-artifact@v1
        with:
          name: db-schemas
          path: schemas

      - name: Upload test coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
